name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-Approve PRs
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'Maverick1872'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"